function addPoints = getAddPoints(time)
    addPoints = -10;
    if time <= 600
        addPoints = 2;
    elseif time <= 800
        addPoints = 1;
    elseif time <= 1000
        addPoints = 0;
    elseif time <= 1100
        addPoints = -1;
    elseif time <= 1200
        addPoints = -2;
    elseif time <= 1300
        addPoints = -3;
    elseif time <= 1400
        addPoints = -4;
    elseif time <= 1500
        addPoints = -5;
    elseif time <= 1600
        addPoints = -6;
    elseif time <= 1700
        addPoints = -7;
    elseif time <= 1800
        addPoints = -8;
    elseif time <= 1900
        addPoints = -9;
    elseif time <= 2000
        addPoints = -10;
    end;